name: Update Requirements

on:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches:
      - main

jobs:
  update-requirements:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install pip-tools
        run: pip install pip-tools

      - name: Compile requirements
        run: pip-compile --upgrade

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          title: "Update requirements.txt"
          body: "This PR updates the requirements.txt file."
          base: main
          branch: update-requirements
          paths: requirements.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
